name: "🐛 Bug Report"
description: Create a new ticket for a bug.
title: "🐛 [BUG] - <title>"
labels:
  - bug
body:
  - type: checkboxes
    id: searched
    attributes:
      label: "Searched for similar issues"
      description: "Have you searched for similar issues before creating this one?"
      options:
        - label: "YES, I have searched for similar issues."
  - type: input
    id: occurred-time
    attributes:
      label: "Time of occurrence"
      description: "When did the issue occur?"
      placeholder: "ex. Today, 9:00 AM"
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: "Device"
      description: "What device are you using?"
      options:
        - MacBook Pro
        - iPhone
        - iPad
        - Android
        - Other
    validations:
      required: false
  - type: input
    id: device-other
    attributes:
      label: "Other Device"
      description: "Please specify the device if you selected 'Other'."
      placeholder: "Enter the device name"
    validations:
      required: false
  - type: input
    id: device-version
    attributes:
      label: "Device Version"
      description: "What is the device version?"
      placeholder: "Enter the device version"
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: "What is the impacted environment?"
      multiple: true
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: "OS Version"
      description: "What is the OS version?"
      placeholder: "Enter the OS version"
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: "What browsers are you seeing the problem on?"
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
    validations:
      required: false
  - type: input
    id: browser-other
    attributes:
      label: "Other Browser"
      description: "Please specify the browser if you selected 'Other'."
      placeholder: "Enter the browser name"
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: "Browser Version"
      description: "What is the browser version?"
      placeholder: "Enter the browser version"
    validations:
      required: false
  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: "Please enter your GitHub URL to provide a reproduction of the issue."
      placeholder: "ex. https://github.com/USERNAME/REPO-NAME"
    validations:
      required: true
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: "Please enter the steps to reproduce the issue."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: markdown
    validations:
      required: true
  - type: textarea
    id: current-result
    attributes:
      label: "Current Result"
      description: "Please enter an explicit description of the current result."
      render: markdown
      placeholder: "Short and explicit description of your incident..."
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots"
      description: "If applicable, add screenshots to help explain your problem."
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: "Logs"
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      render: bash
    validations:
      required: false
  - type: textarea
    id: expected-result
    attributes:
      label: "Expected Result"
      description: "Please describe what you expected to happen."
      render: markdown
      placeholder: "Short and explicit description of your expected result..."
    validations:
      required: true
